version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8001:8000"
    env_file:
      - .docker.env
    depends_on:
      - db

  db:
    image: postgres:13
    env_file:
      - .docker.env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
